### ISSUE TITLE
Aspect Ratio Bug

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#116]
### Max Height

The max height should be 552

### 4:5 Aspect Ratio
- [x] Fix this

  - http://andrew.hedges.name/experiments/aspect_ratio/original.html

#### Places Aspect Ratio Bug
- [x] Fix this
  - The cards load at 240px (approx) then once a user scrolls down and then back up the cards reload to their true size which is 280px (approx.

![places aspect ratio bug](https://cloud.githubusercontent.com/assets/12651511/11405978/0feae018-9360-11e5-8fd8-d653bfadaa45.png)

#### Home
- [x] Fix this
  - The cards load at 425px (approx) then once a user scrolls down and then back up the cards reload to their true size which is 499px (approx)
![home aspect ratio bugs](https://cloud.githubusercontent.com/assets/12651511/11406518/79147b9c-9362-11e5-9cdd-65b6ad7f8b37.png)

**Comment by LucasCoelho** [comment]
@joshrio 
*We should make the max height 4:5 so that the vertical heights are all consistent. The max height of a 4:5 ratio on a 1x device is 400px.
Make aspect ratio 4 | 5 then enter screen width into top right and press calculate too see height.*

Does that mean cropping images that have aspect ratio higher than 5/4?
