### ISSUE TITLE
Profile Settings Issues

### ISSUE THREAD

**Issue by joshrio** [sceene/sprint-planning#84]
- [ ] Profile Images rotate when uploaded
 - Not Fixed. To repeat upload a photo you've taken from your phone.
- [ ] Profile avatars do not update when user uploads new image
- [x] Profile images are being cropped

**Comment by joshrio** [comment]
Email From IMIGIX

Hello Josh,

Thanks for your interest in imgix!  There is a fit parameter which will let you decide how the output image fits your target dimension.  In this instance, I entered fit=crop, which will center the image appropriately in order to always result in a square image and respect your width and height parameters.  You can read more about these here: https://www.imgix.com/docs/reference/size

Here is the sand box preview where I added fit=crop

http://sandbox.imgix.com/view?url=https%3A%2F%2Fassets.imgix.net%2Funsplash%2Fraspberries.jpg%3Fh%3D200%26q%3D95%26fm%3Dpjpg%26chromasub%3D444%26usm%3D10%26w%3D200%26fit%3Dcrop

Please let me know if you have any additional questions about this.

**Comment by LucasCoelho** [comment]
@joshrio 
 Profile avatars do not update when user uploads new image
this involves both iOS and API development
I created an issue on API to solve this
I already made the changes but to fully test we'll need to wait for API
app might behave a little weird because of the changes I made anticipating API (on user profile page only)
